### ISSUE TITLE
Unknown command message

### ISSUE THREAD

**Issue by Matthbo** [boformer/DoubleCheck#3]
when /deny or /confirm is typed correctly, the server still sends a message saying it is an unknown command.
![example](https://cloud.githubusercontent.com/assets/4380412/7472695/759d6e88-f335-11e4-8cb4-d1802111ae21.PNG)

**Comment by boformer** [comment]
I guess this is related to the way Sponge handles commands now.

Please test the following:

write a simple test plugin with only one event handler in the main class:

``` java
@Subscribe(order = Order.LATE)
public void onCommand(CommandEvent event) {
    System.out.println("Cancelling command /" + event.getCommand())
    event.setCancelled(true);
}
```

It will probably produce the same message.

Then try it with different `order` values:
- `Order.PRE`
- `Order.Early`
- `Order.DEFAULT`

If it still posts the same "Unknown Command" message, this is a Sponge Bug.

**Comment by boformer** [comment]
I am not at home, so I can not do it right now.

**Comment by Matthbo** [comment]
It does indeed seem like a sponge bug, i couldn't even stop my server

**Comment by Matthbo** [comment]
I also tried using event.setResult(null), event.setResult(CommandResult.emty()) and event.setResult(CommandResult.success()) but they all seem to give me an error

**Comment by boformer** [comment]
Did you run the tests?

**Comment by Matthbo** [comment]
yeah they all get the same "Unknown command" message

**Comment by boformer** [comment]
Ok, i will report The bug. It probably affects both sponge implementations

**Comment by boformer** [comment]
Another thing: Does The cancelling itself work?

**Comment by Matthbo** [comment]
yeah that works

**Comment by boformer** [comment]
@Matthbo I fixed the issue. The solution is to set the command result to "empty".

The problem is that there is a bug in Sponge right now that throws an error when the result is set.

I will upload the new version to the maven repo when the Sponge issue is fixed.

**Comment by Matthbo** [comment]
Thanks in advance!
